######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 10 16:48:22 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Include Src
INCLUDEPATH += . Include

# Input
HEADERS += Include/enums.h Include/mainWindow.h Include/paintArea.h
SOURCES += Src/main.cpp Src/mainWindow.cpp Src/paintArea.cpp
RESOURCES += MainWindow.qrc
